export { default as About } from './about/About'
export { default as Events } from './events/Events'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Services } from './services/Services'
export { default as Testimonials } from './testimonials/Testimonials'
export { default as Cta } from './cta/Cta'
